# File generated by cwl2click v0.10.0
# timestamp: 2026-09-23T15:58:25.186

__all__ = []

from crop.crop_impl import execute as crop_command

from pathlib import Path

import click







# None
__all__.append("crop")
# NOTE
# Do not forget to add the section below in your `pyproject.toml` file
#  
# [project.scripts]
# crop = "crop.cli:crop"


crop = click.Command(
    name="crop",
    callback=crop_command,
    help="""Crop each requested spectral band to the area of interest.""",
    short_help="""Crop Spectral Bands""",
    params=[
            click.Option(
            ["--input-item"],
            "item",
            type=click.STRING,
            multiple=False,
            required=True,
            is_flag=False,
            help="""URL of the source STAC item.""",
        ),
            click.Option(
            ["--aoi"],
            "aoi",
            type=click.STRING,
            multiple=False,
            required=True,
            is_flag=False,
            help="""GeoJSON polygon defining the area of interest.""",
        ),
            click.Option(
            ["--epsg"],
            "epsg",
            type=click.Choice(['4326']),
            multiple=False,
            required=True,
            is_flag=False,
            help="""Coordinate reference system of the area of interest.""",
        ),
            click.Option(
            ["--band"],
            "band",
            type=click.Choice(['green', 'nir', 'nir08']),
            multiple=False,
            required=True,
            is_flag=False,
            help="""Common name of the spectral band to crop.""",
        ),
    ]
)


