# File generated by cwl2click v0.10.0
# timestamp: 2026-09-23T10:55:05.790

__all__ = []


import click

from crop.crop_impl import execute as crop_command

# None
__all__.append("crop")
# NOTE
# Do not forget to add the section below in your `pyproject.toml` file
#
# [project.scripts]
# crop = "crop.cli:crop"


crop = click.Command(
    name="crop",
    callback=crop_command,
    help="""No info provided""",
    short_help="""No info provided""",
    params=[
        click.Option(
            ["--input-item"],
            "item",
            type=click.STRING,
            multiple=False,
            required=True,
            is_flag=False,
        ),
        click.Option(
            ["--aoi"],
            "aoi",
            type=click.STRING,
            multiple=False,
            required=True,
            is_flag=False,
        ),
        click.Option(
            ["--epsg"],
            "epsg",
            type=click.STRING,
            multiple=False,
            required=True,
            is_flag=False,
        ),
        click.Option(
            ["--band"],
            "band",
            type=click.STRING,
            multiple=False,
            required=True,
            is_flag=False,
        ),
    ],
)
