# File generated by cwl2click v0.10.0
# timestamp: 2026-09-23T15:58:36.669

__all__ = []

from otsu.otsu_impl import execute as otsu_command

from pathlib import Path

import click







# None
__all__.append("otsu")
# NOTE
# Do not forget to add the section below in your `pyproject.toml` file
#  
# [project.scripts]
# otsu = "otsu.cli:otsu"


otsu = click.Command(
    name="otsu",
    callback=otsu_command,
    help="""Apply Otsu thresholding to the NDWI raster to generate a binary water body mask.""",
    short_help="""Otsu Thresholding""",
    params=[
            click.Option(
            ["--raster"],
            "raster",
            type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=True, dir_okay=False),
            multiple=False,
            required=True,
            is_flag=False,
            help="""Normalized difference water index raster to threshold.""",
        ),
    ]
)


