# File generated by cwl2click v0.10.0
# timestamp: 2026-09-23T15:58:29.884

__all__ = []

from norm_diff.norm_diff_impl import execute as norm_diff_command

from pathlib import Path

import click







# None
__all__.append("norm_diff")
# NOTE
# Do not forget to add the section below in your `pyproject.toml` file
#  
# [project.scripts]
# norm_diff = "norm_diff.cli:norm_diff"


norm_diff = click.Command(
    name="norm_diff",
    callback=norm_diff_command,
    help="""Calculate the normalized difference water index (NDWI) from the green and near-infrared spectral band rasters.""",
    short_help="""Normalized Difference Calculation""",
    params=[
            click.Option(
            ["--rasters"],
            "rasters",
            type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=True, dir_okay=False),
            multiple=True,
            required=True,
            is_flag=False,
            help="""Ordered green and near-infrared GeoTIFFs used to calculate NDWI.""",
        ),
    ]
)


