# File generated by cwl2click v0.10.0
# timestamp: 2026-09-23T15:58:42.074

__all__ = []

from stac.stac_impl import execute as stac_command

from pathlib import Path

import click







# None
__all__.append("stac")
# NOTE
# Do not forget to add the section below in your `pyproject.toml` file
#  
# [project.scripts]
# stac = "stac.cli:stac"


stac = click.Command(
    name="stac",
    callback=stac_command,
    help="""Generate a STAC catalog for the water bodies using the source STAC items and the binary water body masks.""",
    short_help="""STAC Generation""",
    params=[
            click.Option(
            ["--item"],
            "item",
            type=click.STRING,
            multiple=True,
            required=True,
            is_flag=False,
            help="""Source STAC item URLs in the same order as the water body masks.""",
        ),
            click.Option(
            ["--rasters"],
            "rasters",
            type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=True, dir_okay=False),
            multiple=True,
            required=True,
            is_flag=False,
            help="""Binary water body masks in the same order as the source STAC items.""",
        ),
    ]
)


